### ISSUE TITLE
Improve samples

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#419]
There are several improvements that I would like to see the samples.  To make it easier for other to help improve the samples, this issue will be an [epic](https://www.atlassian.com/agile/project-management/epics) with a checklist that I keep this first comment updated with (hopefully) simple tasks.

## Primary consolidated sample
I like how [Material Design in XAML Toolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) has [one sample for WPF](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MainDemo.Wpf) that demonstrates everything.  We have a project called Capabilities that is intended to be the start of this consolidated sample.

- [ ] Move the Validation sample into the Capabilities sample.
- [ ] A sample that makes use of stickiness during a transition animation to continue showing the old data.  See [this documentation](https://github.com/elmish/Elmish.WPF/blob/99f9601943e25e574e699ef313b8d3b40c288a70/src/Elmish.WPF/Binding.fs#L1802-L1806).
- [ ] Some interesting uses of adorners (c.f. https://github.com/elmish/Elmish.WPF/issues/292).
- [ ] More samples involving sequences (that are not recursive) (c.f. #247)
- [ ] Contrast `SubModelSeq` binding (merge) performance with and without keys
- [ ] ...

## Patterns
- [ ] CmdMsg pattern
- [ ] OutMsg (with translator) pattern (c.f. https://github.com/elmish/Elmish.WPF/issues/300#issuecomment-738877267).

## Integration with thirds-party controls
If licensing permits, it would be nice to have samples that show how to integrate with third party controls.
- [ ] [DevExpress](https://www.devexpress.com/products/net/controls/wpf/)
- [ ] [Telerik](https://www.telerik.com/products/wpf/overview.aspx)
- [ ] [Syncfusion](https://www.syncfusion.com/products/communitylicense)

## Samples that demonstrate entries points
- [ ] Traditional (i.e. though `App.xmal`).  Advantage: corresponding resource code automatically generated if needed.
- [ ] Explicit entry point in C#
- [ ] Explicit entry point in F#

## Related issues and comments
- https://github.com/elmish/Elmish.WPF/issues/347
- https://github.com/elmish/Elmish.WPF/issues/325

**Comment by Evangelink** [comment]
@TysonMN regarding Telerik, they recommended me to use the "trial version":

> Trial License
The free trial licenses of all Telerik products are fully functional and will work for an unlimited time but with trial error messages (see below) displayed randomly on the page.
>
> Trial Error Messages
The trial licenses will occasionally display the following message on your application:

Telerik UI for WPF trial version. Copyright Telerik © 2002-2014. To remove this message, please, purchase a developer version.

More information on their [website license page](https://docs.telerik.com/devtools/wpf/getting-started/installation/installation-installing-license-limitations-wpf)).

**Comment by TysonMN** [comment]
That seems fine. Let's have it be a separate executable/project then so that message doesn't also get displayed to people not interested in Telerik.

**Comment by rfreytag** [comment]
I found the transition from SingleCounter to NewWindow samples had a learning curve as SingleCounter does not have an App.fs.  I have a working AnotherNewWindow that consoldates models and functions in Program.fs. 

Would that be useful to others?

**Comment by TysonMN** [comment]
Sure.  Share a link to a branch containing your code, and I will take a look.

**Comment by rfreytag** [comment]
I found Sample/NewWindow.Core/App.fs hard to read.  I have a version in [my fork](https://github.com/rfreytag/Elmish.WPF/tree/master), branch: `Adding_fully-specified_parameter_lists` that I find more readable with the following changes:

- Every function has fully-specified parameter lists and return values.  Readability is improved by not having to hover over function names to see what the function manipulates.  

- `module App`, `module Window1` and `module Window2` have been renamed `module App_Window1` and `module App_Window2` so their usage in `App.bindings` is not confused with the actual references to `Window2` in `App.bindings`.

- Clarified `module App`, `module Window1` and `module Window2`: `get`, `set`, and `map` so they specify the type on which they operate for _readability._  They are now respectively:

   - `module Window1`, `get_Window1State1`,  `set_Window1State1`,  and `map_Window1State1` and
   - `module Window2`, `get_Window2`,  `set_Window2`,  `map_Window2`.

- Replaced all usage of `function` with explicit `match <parameter name> with` in line with adding explicit parameter lists.  

Doing this helped me understand what was going on.  I hope it will help others.  I will issue a pull request if you like where I'm going.  Let me know please.

**Comment by marner2** [comment]
@rfreytag Go ahead and open a Pull Request for it. Modify the existing sample and that will make things easier to look at. They all sound good, especially if you found it helpful (empirical testing is the best testing).

**Comment by rfreytag** [comment]
Everything I did is what _I think_ is the minimum necessary changes from the prior Sample for readability.  Perhaps I'm missing your meaning?

**Comment by marner2** [comment]
@rfreytag I'm sorry, somehow I got it in my head that you had suggested you could make it as a separate example project.

I'd say it looks good exactly as you have it, and you should definitely open a PR.

**Comment by TysonMN** [comment]
That sounds good.

My idea with the `Capabilities` sample is that most of the samples would be combined into that one.  Does that make sense?

World you like to do that combining?

**Comment by rfreytag** [comment]
@TysonMN That makes sense.  As you can see I am returning to this after a long absence.  Best if I take bites of this as I can and limit my broad commitments for now.  

It is gratifying to have my thoughts considered; thank you.

**Comment by TysonMN** [comment]
No rush

**Comment by TysonMN** [comment]
That is a reasonable idea. Thanks for suggesting it.

I think improving the existing samples is more important though, so I don't know when (or if) this improvement will happen.

**Comment by YkTru** [comment]
I suggest this example to guide Elmish.WPF newcomers coming from C#+MVVM; it's at least what I would have liked to have as a first tutorial (I think the abstract name says more about the general mindset to have when coming from C#, than a more specific counter-example, which is of course a good next step).

https://github.com/YkTru/Elmish.WPF-Samples-ViewModel/tree/master/ViewModel.Core
